from .octmnist import (
    OCTMNIST_CNV,
    OCTMNIST_DME,
    OCTMNIST_CNV_LABEL,
    OCTMNIST_DME_LABEL,
    OCTMNIST_DRUSEN_LABEL,
    OCTMNIST_NORMAL_LABEL,
)

__all__ = [
    "OCTMNIST_CNV",
    "OCTMNIST_DME",
    "OCTMNIST_CNV_LABEL",
    "OCTMNIST_DME_LABEL",
    "OCTMNIST_DRUSEN_LABEL",
    "OCTMNIST_NORMAL_LABEL",
]
